services:

  informs:
    command: python manage.py runserver 0.0.0.0:8000
    # restart: unless-stopped
    volumes:
      # for development and debugging
      # make the code folder live
      - $PWD/informs/webapp:/opt/app/informs

  queues:
    volumes:
      - $PWD/informs/webapp:/opt/app/informs
